version: "3.0"
services:
  app_xyz:
    build: 
      context: ./src
    container_name: app_xyz
    volumes:
      - ./src/logs:/usr/app/logs
      - ./src/uploads:/usr/app/uploads
      - ./src/.env:/usr/app/.env
    tty: true
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports: 
      - 8000:3000
    networks: 
      - app-network

  db_xyz:
    image: mysql:latest
    container_name: db_xyz
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 127.0.0.1:8001:3306
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge